# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_dt', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('step', models.IntegerField(choices=[(1, 'applied'), (2, 'quiz_started'), (3, 'quiz_completed'), (4, 'onboarding_requested'), (5, 'onboarding_completed'), (6, 'hired'), (7, 'rejected')], default=1)),
            ],
        ),
    ]
