# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='zipcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zip code should be 5 digits. eg. 94085', regex='\\d{5}$')]),
        ),
    ]
